application: pioneering-axe-100211
version: 1
runtime: php55
api_version: 1

handlers:
- url: /
  script: top.php
- url: /convert
  script: convert.php
- url: /show
  script: show.php
- url: /getword
  script: getword.php
- url: /madlib
  script: madlib.php
